### ISSUE TITLE
create an example for android and winit

### ISSUE THREAD

**Issue by coderedart** [coderedart/etk#4]
It is easy enough to do, but having a dedicated template might be good like eframe template repo.

**Comment by AZProductions** [comment]
What about a tao template?

**Comment by coderedart** [comment]
Last time i checked, tao still had some issues. For example, vulkan didn't work. And i had to use a fork of glutin to use opengl, but that had some bad flickering too. So, i gave up on that for now. 

EDIT: links to relevant issues https://github.com/tauri-apps/tao/issues/717 (vulkan) and https://github.com/tauri-apps/tao/issues/322 (opengl). 

It seems tao is being abandoned in favor of upstream winit.

> Tao is kinda of on maintenance mode for now as we are investigating switching back to winit and are extracting the major features of tao into its own crates, such as menus have been extracted to its own crate [tauri-apps/muda](https://github.com/tauri-apps/muda) btw, which exposes the GtkMenu and could potentioally also expose the GtkMenuBar. 

from https://github.com/tauri-apps/tao/issues/717#issuecomment-1532055848

**Comment by coderedart** [comment]
archived
